### ISSUE TITLE
RaidPlanner CB plugin doesn't work with CB 2.0.3

### ISSUE THREAD

**Issue by Erasilia** [Taracque/RaidPlanner#49]
Hi Taracque,

A big "Thank you" for your tool who is really useful for MMO gamers !

I'm writting you this because the CB plugin seems not work CB 2.X :/

http://i.imgur.com/YVAxFst.png

I'm using :
Joomla 2.5.24
Community Builder 2.0.3
RaidPlanner 0.9.1

Thanks for your reply.
Erasilia.

**Comment by Taracque** [comment]
Issue closed as there was no feedback.
