### ISSUE TITLE
Changing calendar view multiple day events

### ISSUE THREAD

**Issue by Flight777** [Taracque/RaidPlanner#50]
Hi Taracque,

First of all thanks for this amazing plugin!! :) 

I'm trying to adjust it so it also displays multiple day events properly. Now, if I saw correctly, it only places a href in the calendar table on the starting date of the event. Seen as in /views/calendar/tmpl/default.php:

```

	if (@$this->events[$thedate]) {
			foreach ($this->events[$thedate] as $event) {
			?>
							
```

I would like to place a href in each day the event will be running, such that you can see the span of the event in the Calendar. However, I'm fairly new to php developing and I don't really understand where and how you build the event/events classes etc. What I think I need to do is to adjust the loop such that it places all events meeting the following requirement: 

```
 event.startingdate =< thedate <= event.enddate 
```

Any directions or help would be highly appreciated and helps me to learn as well :) It might also be very useful for a future version of RaidPlanner. I hope I made my intentions clear, otherwise don't hesitate to ask for more clarification. Thank you very much!

Kind regards,

Rob Vermeij

**Comment by Taracque** [comment]
This will not be implemented, I don't see the real advantage of this. As the calendar shows a list only, and it is not a day planner, only the start time of the events are checked.
