### ISSUE TITLE
Implode error when clicking on a username from calendar event

### ISSUE THREAD

**Issue by muldereric** [Taracque/RaidPlanner#51]
After opening an event from the calendar and clicking on a username from that event, an error is thrown on a blanc page, saying (I escaped all HTML tags with //):
The requested URL /main/<//br /><//b >Warning<///b>: implode() [<//a href='http://php.net/manual/en/function.implode'>function.implode<///a>]: Invalid arguments passed in <//b>./main/components/com_raidplanner/views/event/tmpl/default.php<///b> on line <//b>144<///b><//br /> was not found on this server.

**Comment by Taracque** [comment]
It seems that you have some kind of plugin set. Which one is that? It seems that the plugin gives wrong answer to the onRPGetCharacterLink event.

**Comment by muldereric** [comment]
I have no idea. As far as I know we don’t use any plugins that utilize that event. Any way to find out?

 

Van: Taracque [mailto:notifications@github.com] 
Verzonden: woensdag 21 oktober 2015 20:07
Aan: Taracque/RaidPlanner <RaidPlanner@noreply.github.com>
CC: Eric Mulder <efmulder@ziggo.nl>
Onderwerp: Re: [RaidPlanner] Implode error when clicking on a username from calendar event (#51)

 

It seems that you have some kind of plugin set. Which one is that? It seems that the plugin gives wrong answer to the onRPGetCharacterLink event.

**Comment by Taracque** [comment]
You can check it on the Administration interface of your Joomla installation. Go to Administration/Components/RaidPlanner/Guilds and open your guild. There is a "Sync module" setting there. Please le me know if there anything is set as Sync module

**Comment by muldereric** [comment]
The sync module that is set, is “wow”.

 

Van: Taracque [mailto:notifications@github.com] 
Verzonden: donderdag 22 oktober 2015 13:56
Aan: Taracque/RaidPlanner <RaidPlanner@noreply.github.com>
CC: Eric Mulder <efmulder@ziggo.nl>
Onderwerp: Re: [RaidPlanner] Implode error when clicking on a username from calendar event (#51)

 

You can check it on the Administration interface of your Joomla installation. Go to Administration/Components/RaidPlanner/Guilds and open your guild. There is a "Sync module" setting there. Please le me know if there anything is set as Sync module

**Comment by Taracque** [comment]
Ok, this should be an old WoW Armory plugin. Download the current one from here:
https://github.com/Taracque/RaidPlanner-wow/archive/master.zip
And install it as a Joomla plugin. Once it is installed check that the guild is set up correctly and then check if the problem still exists.

**Comment by muldereric** [comment]
I downloaded and installed the plugin like you said, but still I get the implode error on the hyperlinks...
  The guild can be synchronized from the Battle.net Armory just fine, so it's not that.

**Comment by Taracque** [comment]
Please tell me your guild name and armory region (EU, US etc.)

**Comment by muldereric** [comment]
Spark on EU

-------- Oorspronkelijk bericht --------
Van: Taracque <notifications@github.com> 
Datum: 2015-10-26  13:24  (GMT+01:00) 
Aan: Taracque/RaidPlanner <RaidPlanner@noreply.github.com> 
Cc: Eric Mulder <efmulder@ziggo.nl> 
Onderwerp: Re: [RaidPlanner] Implode error when clicking on a username from
  calendar event (#51) 

Please tell me your guild name and armory region (EU, US etc.)

**Comment by Taracque** [comment]
I guess this is Spark - Runetotem - EU. Do you have this problem with all characters, or only with some of them?
What version of PHP do you have? (You can check it via Administration / System / System Information)
I need the PHP Version and Joomla!Version values.

**Comment by Taracque** [comment]
I've tested with the following setup:

Details
Guild Name: Spark
Sync module: wow

Plugin settings
Realm: Runetotem
Region: EU
Sync now 
Last Sync time: 2015-10-26 13:53:14

And all characters link to their Armory profile (I've tested Kimmý, Druidaa, Maladoron)

**Comment by muldereric** [comment]
Very weird that it is not working for us then. We keep getting the implode errors, no matter what I try

-------- Oorspronkelijk bericht --------
Van: Taracque <notifications@github.com> 
Datum: 2015-10-26  14:03  (GMT+01:00) 
Aan: Taracque/RaidPlanner <RaidPlanner@noreply.github.com> 
Cc: Eric Mulder <efmulder@ziggo.nl> 
Onderwerp: Re: [RaidPlanner] Implode error when clicking on a username from
  calendar event (#51) 

I've tested with the following setup:

Details

Guild Name: Spark

Sync module: wow

Plugin settings

Realm: Runetotem

Region: EU

Sync now 

Last Sync time: 2015-10-26 13:53:14

And all characters link to their Armory profile (I've tested Kimmý, Druidaa, Maladoron)

**Comment by muldereric** [comment]
I have solved the problem. The issue arrises if no guild is selected while creating an event. Just figured out the links work just fine if a guild is selected.
Because we can only define one guild, isn't it an option to select it by default?

**Comment by Taracque** [comment]
Sigh… Well even if you have only one guild in theory you can have guildless characters who are not from your guild but registered on your site. I'll fix this soon, and thanks for pointing that out.

**Comment by muldereric** [comment]
No problem. Glad we figured out where it came from. Until there's a solution I will make sure the guild name will be filled in for each event.Like you said, in theory you could have multiple guilds using the same website. What happens then if they sign up for an event that is not theirs (i.e. other guild)? Is that even possible?

**Comment by Taracque** [comment]
If there is no guild set for a raid, anyone can sign up from any guild.

**Comment by Taracque** [comment]
Fixed in https://github.com/Taracque/RaidPlanner/commit/3a01535bc6c3688258ed58ec672d9abc059b1d33
If you install the current version over your existing one, that issue should be fixed.

**Comment by muldereric** [comment]
I download the complete repo and installed it over the old one. Installation went fine without a hitch.

However when I now go to the guild configuration, I get a message saying 

 

Warning: array_key_exists() expects parameter 2 to be array, string given in /var/www/spark-guild.eu/public_html/administrator/components/com_raidplanner/helper.php on line 83

 

This message is also reflected in the links of the characters on an event.

Do you recommend installing a fresh copy (i.e. uninstalling the current RaidPlanner and reinstalling from a Git clone)?

 

 

Van: Taracque [mailto:notifications@github.com] 
Verzonden: maandag 26 oktober 2015 19:44
Aan: Taracque/RaidPlanner <RaidPlanner@noreply.github.com>
CC: Eric Mulder <efmulder@ziggo.nl>
Onderwerp: Re: [RaidPlanner] Implode error when clicking on a username from calendar event (#51)

 

Fixed in  <https://github.com/Taracque/RaidPlanner/commit/3a01535bc6c3688258ed58ec672d9abc059b1d33> 3a01535
If you install the current version over your existing one, that issue should be fixed.

**Comment by Taracque** [comment]
I'll fix that tomorrow. However warning shouldn't be displayed by php, you should turn the Error reporting to None in System / Global Configuration / Server

**Comment by Taracque** [comment]
Fixed in https://github.com/Taracque/RaidPlanner/commit/7462e413b49a66f170a47a5e1945e3c38d965e7c
