### ISSUE TITLE
Cross-realm support for character links

### ISSUE THREAD

**Issue by muldereric** [Taracque/RaidPlanner#53]
When looking at event details, each signed user has a link to his/her battle.net profile, based on the guild's realm and the character name of the user. However, cross-realm worlds have been introduced long time ago, so better to construct the character link out of the character realm and character name instead of guild realm and character name.

Example of problem:
Guild: Spark @ Runetotem
Character: MyCharacter-Kilrogg

When hoovering over the character in an event you can see the link points to:
http://eu.battle.net/wow/en/character/runetotem/MyCharacter/simple
which is wrong and should be:
http://eu.battle.net/wow/en/character/kilrogg/MyCharacter/simple

**Comment by Taracque** [comment]
This is a bug in the https://github.com/Taracque/RaidPlanner-wow plugin. I've fixed it in version 0.1.0 (https://github.com/Taracque/RaidPlanner-wow/commit/aa293a057a396a51a97cce42ab1db685d5290341)
Just install the latest version, and it hopefully fixes your problem.

**Comment by muldereric** [comment]
Confirmed. Updated the sync addon and the links are now working as expected. Case closed.
