### ISSUE TITLE
auto sync wow plugin not working

### ISSUE THREAD

**Issue by muldereric** [Taracque/RaidPlanner#55]
The wow plugin is set to sync every 8 hours, but it is not syncing at all. Manual sync works fine.

**Comment by Taracque** [comment]
Automatic sync needs a published roster page. If someone (eg. google robot) opens the roster page of the site, and it is not synced in the last xy hours, it makes a sync. That's how it works now. Probably you don't have a published Roster page.

**Comment by muldereric** [comment]
Thank you for the explanation. Added the roster as accessible page and could see the autosync occuring.
